# Integration test to make sure snapd's API doesn't move too far under our feet
name: Daily Integration Test

on:
  schedule:
    # Every day at 12:00-0700
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  snapd_integration_test:
    uses: ./.github/workflows/integration-test.yml
